version: '3.9'

services:

  mongo:
    container_name: mongo-restaurant-container
    build:
      context: ./mongo/
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./mongo/.env
    ports:
      - "55601:27017"
    volumes:
      - mongo:/data/db
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  redis:
    container_name: redis-restaurant-container
    build:
      context: ./redis/
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "55602:6379"
 
  laravel:
    build:
      context: ./api/
      dockerfile: DockerFile
      target : fpm
      args:
        IMAGE: fpm
    container_name: laravel-restaurant-container
    restart: unless-stopped
    volumes:
      - ./api/:/app/api
    ports:
      - "127.0.0.1:9000:9000"
    depends_on:
      - mongo
      - redis

  cli:
    container_name: cli-restaurant-container
    build:
      context: ./api/
      dockerfile: DockerFile
      target: cli
      args:
        IMAGE: cli
    restart: unless-stopped
    volumes:
      - ./api/:/app/api
    depends_on:
      - mongo
      - redis

  nginx:
      container_name: nginx-restaurant-container
      build:
        context: ./nginx/
        dockerfile: Dockerfile
      restart: unless-stopped
      ports:
        - "80:80"
      volumes:
        - ./api/:/app/api:ro
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf             # Nginx main config
        - ./nginx/conf.d:/etc/nginx/conf.d                     # Nginx / config
        - ./nginx/logs:/var/log/nginx                          # nginx logs
      depends_on:
        - laravel
        - admin

  admin:
    build:
      context: ./admin/
      dockerfile: Dockerfile
    container_name: admin-restaurant-container
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./admin:/app/admin
      # - /app/front-client/node_modules # Just dont delete this -_-

volumes:
  mongo:
    driver: local