<?php

namespace App\Services\Response;

enum HttpStatusEnum : string
{
    CONST OK_RESPONSE_CODE = 200 ;
    CONST OK_RESPONSE_TEXT = 'ok' ;

    CONST COLLECTION_RESPONSE_CODE = 270 ;
    CONST COLLECTION_RESPONSE_TEXT = 'collection' ;

    CONST RESOURCE_RESPONSE_CODE = 280 ;
    CONST RESOURCE_RESPONSE_TEXT = 'resource' ;

    CONST MEDIA_RESPONSE_CODE = 290 ;
    CONST MEDIA_RESPONSE_TEXT = 'media' ;

    CONST CUSTOM_ERROR_RESPONSE_CODE = 400 ;
    CONST CUSTOM_ERROR_RESPONSE_TEXT = 'custom error' ;

    CONST UN_AUTHORIZED_RESPONSE_CODE = 401 ;
    CONST UN_AUTHORIZED_RESPONSE_TEXT = 'Unauthorized' ;

    CONST FORBIDDEN_RESPONSE_CODE = 403 ;
    CONST FORBIDDEN_RESPONSE_TEXT = 'forbidden' ;

    CONST INVALID_PARAMS_RESPONSE_CODE = 470 ;
    CONST INVALID_PARAMS_RESPONSE_TEXT = "invalid params" ;

    CONST ENTITY_NOT_FOUND_RESPONSE_CODE = 480 ;
    CONST ENTITY_NOT_FOUND_RESPONSE_TEXT = "entity not found" ;

    CONST OTP_RESPONSE_CODE = 490 ;
    CONST OTP_RESPONSE_TEXT = "OTP" ;

    CONST ACCESS_REQUIRED_RESPONSE_CODE = 495 ;
    CONST ACCESS_REQUIRED_RESPONSE_TEXT = 'Access required' ;

    CONST REPORTABLE_ERROR_RESPONSE_CODE = 570 ;
    CONST REPORTABLE_ERROR_RESPONSE_TEXT = "error" ;

    CONST ACCESS_DENIED_FOR_IP_ERROR_RESPONSE_CODE = 580 ;
    CONST ACCESS_DENIED_FOR_IP_ERROR_RESPONSE_TEXT = "Unauthorized ip address!" ;

    CONST UN_REPORTABLE_ERROR_RESPONSE_CODE = 500 ;
    CONST UN_REPORTABLE_ERROR_RESPONSE_TEXT = "server error" ;

}
