ARG IMAGE

FROM php:8.1-${IMAGE}-alpine as builder

# libjpeg-turbo-dev freetype-dev libpng-dev libwebp-dev => gd
# $PHPIZE_DEPS curl-dev pkgconfig openssl openssl-dev => mongo
# supervisor => supervisor
# postgresql-dev => postgress
# composer => composer
RUN apk add --no-cache pcre-dev $PHPIZE_DEPS supervisor curl-dev pkgconfig openssl openssl-dev libjpeg-turbo-dev freetype-dev libpng-dev libwebp-dev postgresql-dev composer;

RUN pecl channel-update pecl.php.net ;

# redis
RUN pecl install redis && docker-php-ext-enable redis.so

# mongo
RUN pecl install mongodb && docker-php-ext-enable mongodb && pecl config-set php_ini /usr/local/etc/php/php.ini ;

# gd
RUN docker-php-ext-configure gd --with-jpeg --with-webp --with-freetype && docker-php-ext-install gd ;

# opcache
RUN docker-php-ext-install opcache ;

# tokenizer
RUN docker-php-ext-install tokenizer

# php.ini config
COPY .docker/php/php.ini /usr/local/etc/php/php.ini

# cron config
COPY ./.docker/cron/laravel /etc/crontabs/root

# supervisor config
COPY .docker/supervisor/supervisord.conf /etc/supervisor/conf.d/supervisord.conf

# clear
RUN rm -rf /tmp/* && rm -rf /var/cache/apk/*


FROM builder as  cli

WORKDIR /app/api

CMD ["/usr/bin/supervisord","-c","/etc/supervisor/conf.d/supervisord.conf"]

FROM builder as  fpm

WORKDIR /app/api

EXPOSE 9000

CMD ["php-fpm"]
